package com.ontologycentral.osmwrap.webapp;

import com.ontologycentral.osmwrap.AcceptHeader;

import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.apache.jena.datatypes.xsd.XSDDatatype;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.riot.Lang;
import org.apache.jena.riot.RDFWriter;

/**
 * Handles container error pages for all status codes listed in web.xml.
 * Returns RDF (Turtle/RDF-XML/N-Triples, negotiated) for RDF clients, HTML
 * for browsers, JSON otherwise.
 */
@SuppressWarnings("serial")
public class ErrorServlet extends HttpServlet {

    private static final String NS_HTTP = "http://www.w3.org/2011/http#";
    private static final String NS_HTTP_METHODS = "http://www.w3.org/2011/http-methods#";
    private static final String NS_HTTP_STATUS = "http://www.w3.org/2011/http-statusCodes#";
    private static final String NS_PROV = "http://www.w3.org/ns/prov#";

    private static final Map<Integer, String> REASON_PHRASES = Map.of(
            400, "Bad Request", 404, "Not Found", 406, "Not Acceptable",
            429, "Too Many Requests", 500, "Internal Server Error",
            502, "Bad Gateway", 504, "Gateway Timeout");

    // Individuals the http-statusCodes (2011) vocabulary actually defines —
    // it predates RFC 6585, so 429 has no individual there; those codes fall
    // back to the plain statusCodeValue/reasonPhrase literals only.
    private static final Map<Integer, String> STATUS_CODE_INDIVIDUALS = Map.of(
            400, "BadRequest", 404, "NotFound", 406, "NotAcceptable",
            500, "InternalServerError", 502, "BadGateway", 504, "GatewayTimeout");

    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        Integer status = (Integer) req.getAttribute("jakarta.servlet.error.status_code");
        String message = (String) req.getAttribute("jakarta.servlet.error.message");
        int statusCode = status != null ? status : 500;
        if (message == null || message.isBlank()) message = defaultMessage(statusCode);

        String contextPath = req.getContextPath();
        String requestUri = (String) req.getAttribute("jakarta.servlet.error.request_uri");
        if (requestUri != null && contextPath != null && requestUri.startsWith(contextPath)) {
            requestUri = requestUri.substring(contextPath.length());
        }
        String msg = message;
        if (statusCode == 404) {
            // If the message contains the context path it was generated by Tomcat's DefaultServlet —
            // ignore it and build a clean path from the request URI attribute instead.
            boolean msgHasContextPath = contextPath != null && !contextPath.isEmpty()
                    && message.contains(contextPath);
            if (msgHasContextPath) msg = "Not found" + (requestUri != null ? ": " + requestUri : "");
        }

        resp.setStatus(statusCode);

        List<AcceptHeader.AcceptType> accepted = AcceptHeader.parse(req.getHeader("Accept"));
        double turtleQ = AcceptHeader.maxQ(accepted, "text", "turtle");
        double rdfxmlQ = AcceptHeader.maxQ(accepted, "application", "rdf+xml");
        double ntripQ  = AcceptHeader.maxQ(accepted, "application", "n-triples");
        double rdfQ = Math.max(turtleQ, Math.max(rdfxmlQ, ntripQ));
        double htmlQ = AcceptHeader.maxQ(accepted, "text", "html");
        double jsonQ = AcceptHeader.maxQ(accepted, "application", "json");

        if (rdfQ > 0 && rdfQ > htmlQ && rdfQ > jsonQ) {
            // RDF client: describe the failed HTTP transaction with the W3C
            // HTTP vocabulary (http://www.w3.org/2011/http#) — a Request and
            // a Response as separate blank nodes, linked by http:resp (domain
            // Request, range Response) — plus the same PROV attribution every
            // other document in this wrapper carries on <>, instead of
            // unconditionally falling back to JSON regardless of Accept/
            // conneg. req.getQueryString() still answers the ORIGINAL failing
            // request's query even after the error-page dispatch (confirmed:
            // none of the servlet-spec forward/error attributes carry it, but
            // the request object itself does) — without it, every error for
            // the same path would mint the SAME identifier regardless of the
            // actual query.
            String origin = ProvUtil.effectiveOrigin(req);
            String queryString = req.getQueryString();
            String docUrl = origin + (requestUri != null ? requestUri : "/error")
                    + (queryString != null ? "?" + queryString : "");

            Model model = ModelFactory.createDefaultModel();
            Resource doc = model.createResource(docUrl);
            Property genTime = model.createProperty(NS_PROV + "generatedAtTime");
            Property attrTo = model.createProperty(NS_PROV + "wasAttributedTo");
            doc.addProperty(genTime, model.createTypedLiteral(Instant.now().toString(), XSDDatatype.XSDdateTime));
            doc.addProperty(attrTo, model.createResource(origin + "/index#osmwrap"));

            Resource httpReq = model.createResource();
            Resource httpResp = model.createResource();
            httpReq.addProperty(org.apache.jena.vocabulary.RDF.type, model.createResource(NS_HTTP + "Request"));
            httpReq.addProperty(model.createProperty(NS_HTTP + "requestURI"), docUrl);
            httpReq.addProperty(model.createProperty(NS_HTTP + "mthd"),
                    model.createResource(NS_HTTP_METHODS + req.getMethod().toUpperCase(java.util.Locale.ROOT)));
            httpReq.addProperty(model.createProperty(NS_HTTP + "resp"), httpResp);

            httpResp.addProperty(org.apache.jena.vocabulary.RDF.type, model.createResource(NS_HTTP + "Response"));
            String statusIndividual = STATUS_CODE_INDIVIDUALS.get(statusCode);
            if (statusIndividual != null) {
                httpResp.addProperty(model.createProperty(NS_HTTP + "sc"),
                        model.createResource(NS_HTTP_STATUS + statusIndividual));
            }
            httpResp.addProperty(model.createProperty(NS_HTTP + "statusCodeValue"), String.valueOf(statusCode));
            httpResp.addProperty(model.createProperty(NS_HTTP + "reasonPhrase"),
                    REASON_PHRASES.getOrDefault(statusCode, "Error"));
            httpResp.addProperty(model.createProperty(NS_HTTP + "body"), msg);

            boolean wantsNtriples = ntripQ > turtleQ && ntripQ >= rdfxmlQ;
            boolean wantsTurtle = !wantsNtriples && turtleQ >= rdfxmlQ;
            Lang lang = wantsNtriples ? Lang.NTRIPLES : wantsTurtle ? Lang.TURTLE : Lang.RDFXML;
            String contentType = wantsNtriples ? "application/n-triples;charset=UTF-8"
                    : wantsTurtle ? "text/turtle;charset=UTF-8" : "application/rdf+xml;charset=UTF-8";

            ByteArrayOutputStream buf = new ByteArrayOutputStream();
            RDFWriter.create().lang(lang).base(docUrl).source(model).output(buf);
            resp.setContentType(contentType);
            resp.getOutputStream().write(buf.toByteArray());
        } else if (htmlQ > jsonQ) {
            // Browser: return minimal HTML
            resp.setContentType("text/html;charset=UTF-8");
            String escaped = escHtml(msg);
            resp.getOutputStream().write(("<!DOCTYPE html><html><head><title>Error " + statusCode
                    + "</title></head><body><h1>Error " + statusCode + "</h1><p>"
                    + escaped + "</p></body></html>").getBytes(StandardCharsets.UTF_8));
        } else {
            // API client: return JSON
            resp.setContentType("application/json;charset=UTF-8");
            resp.getOutputStream().write(("{\"error\":" + jsonString(msg) + "}").getBytes(StandardCharsets.UTF_8));
        }
    }

    private static String defaultMessage(int status) {
        switch (status) {
            case 400: return "Bad Request";
            case 404: return "Not Found";
            case 406: return "Not Acceptable";
            case 413: return "Content Too Large";
            case 429: return "Too Many Requests";
            case 500: return "Internal Server Error";
            case 502: return "Bad Gateway";
            case 503: return "Service Unavailable";
            case 504: return "Gateway Timeout";
            default:  return "Error";
        }
    }

    private static String jsonString(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r") + "\"";
    }

    private static String escHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
